framework:
    default_locale: en
    translator:
        enabled: false #d√©sactive la traduction (et vire les erreurs dans la debug bar)
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
